name: windowsci

on: [push]

jobs:
  buildvsx86:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
    - name: main
      working-directory: gep/Project/win32/
      run: |
           dir
           msbuild gepwin32_2022.vcxproj -m /property:Configuration=Release /property:Platform=x86 /verbosity:minimal
    - name: main
      working-directory: SNESticle/Project/win32/
      run: |
           dir
           msbuild win32_2022.vcxproj -m /property:Configuration=Release /property:Platform=x86 /verbosity:minimal
    - name: main64
      working-directory: gep/Project/win32/
      run: |
           dir
           msbuild gepwin32_2022.vcxproj -m /property:Configuration=Release /property:Platform=x64 /verbosity:minimal
    - name: main64
      working-directory: SNESticle/Project/win32/
      run: |
           dir
           msbuild win32_2022.vcxproj -m /property:Configuration=Release /property:Platform=x64 /verbosity:minimal           
    - name: upload
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            Release/*.exe
            x64/Release/*.exe
#  build:
#    runs-on: ubuntu-latest
#    container: ps2dev/gskit:latest
#    steps:
#    - uses: actions/checkout@v2        
#    - name: Install dependencies
#      run: |
#        apk add build-base git bash cmake
#        export PS2DEV=/usr/local/ps2dev
#        export PS2SDK=$PS2DEV/ps2sdk
#        export GSKIT=$PS2DEV/gsKit
#        export PATH=$PATH:$PS2DEV/bin:$PS2DEV/ee/bin:$PS2DEV/iop/bin:$PS2DEV/dvp/bin:$PS2SDK/bin
#        export DEV=$PS2DEV
#        ls $PS2DEV
#        ls $PS2DEV/ee/bin
#        ls $PS2DEV/iop/bin
#        ls $PS2DEV/dvp/bin
#        ls $PS2SDK/bin
#    - name: Compile project
#      run: |
#        cd SNESticle/Project/ps2
#        make -j$(getconf _NPROCESSORS_ONLN)    
